name: Brew tap and deploy

on: push
#   pull_request:
#     branches: 
#       - main
#     types: [closed]

jobs:
    # brew_build:
    #     name: brew tap and deploy
    #     runs-on: macos-latest
    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@master
    #         - name: Bump Brew
    #           shell: bash
    #           env: 
    #             HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.BREW_TOKEN }}
    #           run: |
    #             cd /Users/runner/work/rust-cli-med/rust-cli-med/build/brew
    #             pwd
    #             ls -la
    #             chmod +x ./brew_tap.sh
    #             ./brew_tap.sh
    macos-X86-release:
      name: release macos x86 release
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@master
        - name: check toolchain
          run: rustup default
        - name: Build
          run: |
            cargo build --release
        - name: tar
          run: |
            cp -R demo target/release/ 
            mkdir target/release/med-0.6.2
            mv target/release/med target/release/med-0.6.2
            tar --directory=target/release -cf macos_x86_archive-med-0.6.2.tar.gz med-0.6.2 demo/
        - name: Set SHA
          id: shasum
          run: |
            echo ::set-output name=sha::"$(shasum -a 256 target/release/macos_x86_archive-0.6.2.tar.gz | awk '{printf $1}')"
        - name: Upload binaries x86 to release  
          uses: softprops/action-gh-release@v1
          with:
            tag_name: 0.6.2
            files: 'macos_x86_archive-0.6.2.tar.gz'
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Bump brew
          env: 
            HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.BREW_TOKEN }}
          run: |
              echo ">>> brew tap"
              brew tap jayhuang75/med

              echo ">>> brew bump formula pr"
              echo ${{ steps.shasum.outputs.sha }}
              brew bump-formula-pr -v --version=0.6.2 --no-browse --no-audit --sha256=${{ steps.shasum.outputs.sha }} --url="https://github.com/jayhuang75/rust-cli-med/releases/download/0.6.2/macos_x86_archive-0.6.2.tar.gz" jayhuang75/med/med