name: Brew tap and deploy

on: push
#   pull_request:
#     branches: 
#       - main
#     types: [closed]

jobs:
    brew_build:
        name: brew tap and deploy
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Bump Brew
              env: 
                HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                cd /Users/runner/work/rust-cli-med/rust-cli-med
                pwd
                ls -la
                sudo /build/brew/brew_tap.sh
                