name: Rpm

on: push

jobs:
    rpm_build:
        name: rpm build
        runs-on: ubuntu-latest
        container: docker.io/fedora:latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            
            - name: build
              shell: bash
              run: |
                echo ">>> write to ~/.config/copr"
                touch ~/.config/copr
                echo $FEDORA_COPR >> ~/.config/copr

                echo ">>> running build script"
                ./build/build.sh
              env:
                FEDORA_COPR: ${{secrets.FEDORA_COPR}}