name: Rpm

on: push

jobs:
    rpm_build:
        name: rpm build
        runs-on: ubuntu-latest
        container: docker.io/fedora:latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            
            - name: build
              shell: bash
              run: |
                echo ">>> running build script"
                pwd
                ./build/build.sh