name: Rpm

on: push

jobs:
    rpm_build:
        name: rpm build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            
            - name: build
              shell: bash
              run: |
                echo ">>> setup build dir SOURCES & SPECS"
                mkdir -p ~/rpmbuild/SOURCES ~/rpmbuild/SPECS
                
                echo ">>> entre to SOURCES"
                cd ~/rpmbuild/SOURCES
                pwd

                echo ">>> wget source file"
                wget https://github.com/jayhuang75/rust-cli-med/releases/download/0.6.0/test-med-x86-unknow-linux-gnu-0.6.0.tar.gz -q

                echo ">> tar"
                file test-med-x86-unknow-linux-gnu-0.6.0.tar.gz
                tar -xf test-med-x86-unknow-linux-gnu-0.6.0.tar.gz
                cp med-0.6.0/med /home/runner/rpmbuild

                echo ">>> move spec file from source code"
                cp /home/runner/work/rust-cli-med/rust-cli-med/build/med.spec /home/runner/rpmbuild/SPECS

                echo ">>> build the spec"
                cd /home/runner/rpmbuild
                ls
                rpmbuild -ba --build-in-place --define "_topdir $(pwd)/rpm" SPECS/med.spec



