name: Rpm

on: push

jobs:
    rpm_build:
        name: rpm build
        runs-on: ubuntu-latest
        container: docker.io/fedora:latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            
            - name: build
              shell: bash
              run: |
                echo ">>> write to ~/.config/copr"
                printf "login = $FEDORA_LOGIN" >> ./build/fedora_conf
                printf "username = $FEDORA_USERNAME" >> ./build/fedora_conf
                printf "token = $FEDORA_TOKEN" >> ./build/fedora_conf
                cat ./build/fedora_conf

                echo ">>> running build script"
                ./build/build.sh
              env:
                FEDORA_LOGIN : ${{ secrets.FEDORA_LOGIN }}
                FEDORA_TOKEN : ${{ secrets.FEDORA_TOKEN }}
                FEDORA_USERNAME: ${{ secrets.FEDORA_USERNAME }}