name: Rpm

on: push

jobs:
    rpm_build:
        name: rpm build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            
            - name: build
              shell: bash
              run: |
                echo ">>> setup build dir SOURCES & SPECS"
                mkdir -p ~/rpmbuild/rpm/SOURCES ~/rpmbuild/rpm/SPECS ~/rpmbuild/rpm/BUILD
                
                echo ">>> cd to SOURCES"
                cd ~/rpmbuild/rpm/SOURCES
                pwd

                echo ">>> wget source file"
                wget https://github.com/jayhuang75/rust-cli-med/releases/download/0.6.0/test-med-x86-unknow-linux-gnu-0.6.0.tar.gz

                echo ">>> move spec file from source code"
                pwd
                cp /home/runner/work/rust-cli-med/rust-cli-med/build/med.spec /home/runner/rpmbuild/rpm/SPECS
                cd /home/runner/rpmbuild
                tree

                echo ">>> build the spec"
                pwd
                tree
                rpmbuild -ba --build-in-place --define "_topdir $(pwd)/rpm" SPECS/med.spec
                tree



