name: Rpm

on: push

jobs:
    rpm_build:
        name: rpm build
        runs-on: ubuntu-latest
        container: docker.io/fedora:latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            
            - name: build
              shell: bash
              run: |
                echo ">>> setup "
                sudo dnf install fedora-packager rpmdevtools tree wget gcc -y -q
                rpmdev-setuptree
                pwd
                ls -la
                
                echo ">>> entre SOURCES dir"
                cd ~/rpmbuild/SOURCES

                echo ">>> wget source file"
                wget https://github.com/jayhuang75/rust-cli-med/releases/download/0.6.0/test-med-x86-unknow-linux-gnu-0.6.0.tar.gz -q


                echo ">>> move spec file"
                cp /build/med.spec ~/rpmbuild/SPECS

                echo ">>> build the spec"
                cd ~/rpmbuild
                rpmbuild -ba --build-in-place --define "_topdir $(pwd)" SPECS/med.spec



