name: Test

on:
  push:
    branches:
      - "*"
  pull_request:

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    # necessary for windows
    shell: bash

jobs:
  build:
    name: Publish to Github
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target: [x86_64-unknown-linux-gnu,x86_64-unknown-linux-musl]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          #strip target/${{ matrix.target }}/release/med
          cd target/${{ matrix.target }}/release          
          tar czvf ../../../med-${{ matrix.target }}.tar.gz med
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
            files: 'med*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}