name: Release

# on:
#   release:
#     types: [created]

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [development]

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  build:
    strategy:
      matrix:
        name:
          - linux-x86-64-gnu
          - linux-x86-64-musl
          - linux-armv7-gnu
          - linux-arm64-gnu
          - mac-x86-64
          - windows-x86-64
        include:
          - name: linux-x86-64-gnu
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cross: false

          - name: linux-x86-64-musl
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            cross: true
            features:
              - vendored-openssl

          - name: linux-armv7-gnu
            os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            cross: true
            features:
              
              - vendored-openssl

          - name: linux-arm64-gnu
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            cross: true
            features:
              - vendored-openssl

          - name: mac-x86-64
            os: macos-latest
            target: x86_64-apple-darwin
            cross: false              

          - name: windows-x86-64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            cross: false              

    name: Binaries for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3.0.11
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('Cargo.lock') }}
      - uses: actions/cache@v3.0.11
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('Cargo.lock') }}
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505
        name: Build
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --release --locked --features "${{ join(matrix.features, ',') }}" --target ${{ matrix.target }}
      - name: Package
        shell: bash
        run: |
          ext=""
          [[ "${{ matrix.name }}" == windows-* ]] && ext=".exe"
          bin="../target/${{ matrix.target }}/release/med${ext}"
          version=$(echo "${{ github.ref }}" | cut -d/ -f4)
          dst="med-${{ matrix.target }}-${version}"
          mkdir "$dst"
          mv "$bin" "$dst/"
          mv README.md CHANGELOG.md"$dst/"
      - name: Archive (tar)
        if: '! startsWith(matrix.name, ''windows-'')'
        shell: bash
        run: |
          version=$(echo "${{ github.ref }}" | cut -d/ -f4)
          dst="med-${{ matrix.target }}-${version}"
          tar cavf "../$dst.tgz" "$dst"
      - name: Archive (zip)
        if: startsWith(matrix.name, 'windows-')
        shell: bash
        run: |
          version=$(echo "${{ github.ref }}" | cut -d/ -f4)
          dst="med-${{ matrix.target }}-${version}"
          7z a "../$dst.zip" "$dst"
      - uses: softprops/action-gh-release@c9b46fe7aad9f02afd89b12450b780f52dacfb2d
        with:
          files: |
            med-*.tgz
            med-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}