name: Winget testing

on: push

jobs:
    winget_build_deploy:
        name: winget build and deploy
        runs-on: windows-latest
        steps:
            - name: Check Out Code
              uses: actions/checkout@master
            - name: Build
              run: |
                cargo build --release
            - name: tar
              run: |
                $pwd
                # cd D:\a\rust-cli-med\rust-cli-med\target\release
                # $pwd
                Copy-Item 'D:\a\rust-cli-med\rust-cli-med\demo\*' -Destination 'D:\a\rust-cli-med\rust-cli-med\target\release' -Recurse -Force -Verbose
                tar --directory=target/release -cf win_msvc_archive-0.6.2.tar.gz med.exe demo
            - name: Upload binaries to release  
              uses: softprops/action-gh-release@v1
              with:
                tag_name: 0.6.2
                files: 'win_msvc_archive-0.6.2.tar.gz'
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}